name: Release URL Shortener

on:
  push:
    branches:
      - "main"
    paths:
      - 'url_shortener/**'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version
        id: package-version
        run: |
          VERSION=$(cat url_shortener/version)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: "[Frontend] Build and push image"
        uses: docker/build-push-action@v5
        with:
          context: ./url_shortener/frontend
          file: ./url_shortener/frontend/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}/url-shortener/frontend:${{ env.VERSION }}
          cache-from: type=gha,scope=url-shortener-frontend
          cache-to: type=gha,mode=max,scope=url-shortener-frontend

      - name: "[Redirect-Service] Build and push image"
        uses: docker/build-push-action@v5
        with:
          context: ./url_shortener/services/redirect-service
          file: ./url_shortener/services/redirect-service/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}/url-shortener/redirect-svc:${{ env.VERSION }}
          cache-from: type=gha,scope=url-shortener-redirect-service
          cache-to: type=gha,mode=max,scope=url-shortener-redirect-service
          build-args: |
            VERSION=${{ env.VERSION }}
            BUILD_TIME=${{ github.event.head_commit.timestamp }}
            COMMIT_SHA=${{ github.sha }}

      - name: "[Shortener-Service] Build and push image"
        uses: docker/build-push-action@v5
        with:
          context: ./url_shortener/services/shortener-service
          file: ./url_shortener/services/shortener-service/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}/url-shortener/shortener-svc:${{ env.VERSION }}
          cache-from: type=gha,scope=url-shortener-shortener-service
          cache-to: type=gha,mode=max,scope=url-shortener-shortener-service
          build-args: |
            VERSION=${{ env.VERSION }}
            BUILD_TIME=${{ github.event.head_commit.timestamp }}
            COMMIT_SHA=${{ github.sha }}
